name: Java CD (Deploy to GCP)

on:
  workflow_run:
    workflows: ["Java CI with Gradle (PR & Push)"]
    types: [completed]
    branches: [ "dev" ]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: SSH Deploy
        env:
          # 1. 실행할 전체 스크립트를 환경 변수로 정의 (들여쓰기 걱정 NO!)
          DEPLOY_SCRIPT: |
            echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login -u '${{ secrets.DOCKER_USER_NAME }}' --password-stdin
            cat <<'EOF' > ~/docker-compose.yml
            ${{ secrets.YAML_COMPOSE }}
            EOF
            sudo /usr/local/bin/docker-compose -f ~/docker-compose.yml pull
            sudo /usr/local/bin/docker-compose -f ~/docker-compose.yml up -d
            sudo docker image prune -f
        run: |
          # 2. 정의된 스크립트를 gcloud를 통해 서버로 전달
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
            --zone=${{ secrets.GCP_VM_ZONE }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="$DEPLOY_SCRIPT"
