name: Java CD (Deploy to GCP)

on:
  workflow_run:
    workflows: ["Java CI with Gradle (PR & Push)"]
    types: [completed]
    branches: [ "dev" ]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: SSH Deploy
        run: |
          # 1. 실행할 명령어를 변수로 깔끔하게 정의 (빨간 줄 방지)
          DEPLOY_CMD="
            echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login -u '${{ secrets.DOCKER_USER_NAME }}' --password-stdin && \
            echo '${{ secrets.YAML_COMPOSE }}' > ~/docker-compose.yml && \
            sudo /usr/local/bin/docker-compose -f ~/docker-compose.yml pull && \
            sudo /usr/local/bin/docker-compose -f ~/docker-compose.yml up -d && \
            sudo docker image prune -f
          "

          # 2. 정의한 명령어를 한 번에 실행
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
            --zone=${{ secrets.GCP_VM_ZONE }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command=\"$DEPLOY_CMD\"